#!/bin/bash
#
#SBATCH --mail-user=erbaclaire@cs.uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/home/erbaclaire/slurm/out/%j.%N.stdout
#SBATCH --error=/home/erbaclaire/slurm/out/%j.%N.stderr
#SBATCH --workdir=/home/erbaclaire/mpcs52060/erbaclaire/proj3/src/scraper
#SBATCH --partition=general
#SBATCH --job-name=erbaclaire_proj3
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=1000

module load golang/1.14.1
python3 timer-and-plot.py
